### ISSUE TITLE
State of Lacycom?

### ISSUE THREAD

**Issue by sjuergen** [simatic-ax/lacyccom#1]
Hey guys, thanks for contributing...

but what's the current state of the library?
- is it functionally in a state, so that we can publish it?
- before publishing, we need to do some clearings (ECC, OSS, Patent)... I'll support you in this case
- are there some open points?

Please give me a feedback. 
@sjuergen

**Comment by ThKindler** [comment]
Hey Jürgen,
thanks for taking care. The library is ready to be released
